### PR TITLE
Various cleanups

### PR DESCRIPTION
**Pull request by dridi**
Hi,

I went through the code base and build system and did some improvements in various areas. On my system (up to date Fedora 24) the pre-loaded malloc doesn't work, it hangs unless I compile it with optimizations disabled. It smells like undefined behavior.

I haven't used libumem at scale yet, but I plan to play further with it at some indefinite point.

Next time I'll try with all+extra warnings.

Cheers

### CODE REVIEW

**Comment by dbermond** [comment]
@Dridi 
This pull request fixes building in Arch Linux. Currently ussing gcc 6.3.1.
Thanks for the excellent work!

**Comment by dridi** [comment]
@bermond it might still have problems, I didn't get rid of all undefined behavior and submitted this as a first batch. This repo has been sleeping for the last 6 years, I only hope it's not dead.

**Comment by dbermond** [comment]
@Dridi 
I understand. It looks like developers loosed interest.
I also hope it's not dead and that you can continue with these nice patches. :)

**Comment by postwait** [comment]
Hi there.  We don't current use portableumem, as we run mostly on Illumos and there is actual libumem there.  If you are interested in participating in this project, we can talk about making you a committer.

**Comment by dridi** [comment]
@postwait I don't think I could assume maintenance of portableumem by myself. I did a first sweep through the code base to at least make it build and run (modulus malloc bugs) on my system (and apparently on arch linux too=). In the mean time Varnish removed libumem support altogether so I'm not convinced I will try this at scale anytime soon.

After a quick glance at illumos-gate, I can see why making libumem portable is a project of its own!

**Pull request closed without merging**
